export enum APP_STATE {
  SET_LOADING = 'APP_STATE/SET_LOADING',
  SET_CITY = 'APP_STATE/SET_CITY',
  GET_DANCE_STYLES = 'APP_STATE/GET_DANCE_STYLES',
  SET_DANCE_STYLES = 'APP_STATE/SET_DANCE_STYLES',
  GET_EVENT_TYPES = 'APP_STATE/GET_EVENT_TYPES',
  SET_EVENT_TYPES = 'APP_STATE/SET_EVENT_TYPES',
  SET_COUNTRIES = 'APP_STATE/SET_COUNTRIES',
  GET_COUNTRIES = 'APP_STATE/GET_COUNTRIES',
}
