export enum APP_STATE {
  SET_LOADING = 'APP_STATE/SET_LOADING',
  SET_CITY = 'APP_STATE/SET_CITY',
  GET_DANCE_STYLES = 'APP_STATE/GET_DANCE_STYLES',
  SET_DANCE_STYLES = 'APP_STATE/SET_DANCE_STYLES',
  GET_EVENT_TYPES = 'APP_STATE/GET_EVENT_TYPES',
  SET_EVENT_TYPES = 'APP_STATE/SET_EVENT_TYPES',
  SET_COUNTRIES = 'APP_STATE/SET_COUNTRIES',
  SET_REGIONS = 'APP_STATE/SET_REGIONS',
  GET_COUNTRIES = 'APP_STATE/GET_COUNTRIES',

  SET_STRIPE_KEY = 'APP_STATE/SET_STRIPE_KEY',
  GET_STRIPE_KEY = 'APP_STATE/GET_STRIPE_KEY',

  SET_ERROR_NOTICE_VISIBLE = 'APP_STATE/SET_ERROR_NOTICE_VISIBLE',
  SET_ERROR_NOTICE_MESSAGE = 'APP_STATE/SET_ERROR_NOTICE_MESSAGE',

  SET_CURRENT_COUNTRY = 'APP_STATE/SET_CURRENT_COUNTRY',

  SET_CURRENT_LANGUAGE = 'APP_STATE/SET_CURRENT_LANGUAGE',

  SET_TICKET_PERCENT = 'APP_STATE/SET_TICKET_PERCENT',
  GET_TICKET_PERCENT = 'APP_STATE/GET_TICKET_PERCENT',

  SEND_NOTIFICATION = 'APP_STATE/SEND_NOTIFICATION',

  GET_IS_CHANGE_LANGUAGE = 'APP_STATE/GET_IS_CHANGE_LANGUAGE',
  SET_IS_CHANGE_LANGUAGE = 'APP_STATE/SET_IS_CHANGE_LANGUAGE',

  GET_TYPE_COMMUNITY = 'APP_STATE/GET_TYPE_COMMUNITY',
  SET_TYPE_COMMUNITY = 'APP_STATE/SET_TYPE_COMMUNITY',

  SET_DEV_MODE = 'APP_STATE/SET_DEV_MODE',
}
