export enum REGISTRATION_WITH_EMAIL {
  REQUEST = 'AUTH/REGISTRATION_WITH_EMAIL_REQUEST',
  SUCCESS = 'AUTH/REGISTRATION_WITH_EMAIL_SUCCESS',
  FAIL = 'AUTH/REGISTRATION_WITH_EMAIL_FAIL',
  SET_DATA_REQUEST = 'AUTH/REGISTRATION_SET_DATA_REQUEST',
  SET_DATA_SUCCESS = 'AUTH/REGISTRATION_SET_DATA_SUCCESS',
  SET_DATA_FAIL = 'AUTH/REGISTRATION_SET_DATA_FAIL ',
}
export enum AUTHORIZATION_WITH_EMAIL {
  REQUEST = 'AUTH/AUTHORIZATION_WITH_EMAIL_REQUEST',
  SUCCESS = 'AUTH/AUTHORIZATION_WITH_EMAIL_SUCCESS',
  FAIL = 'AUTH/AUTHORIZATION_WITH_EMAIL_FAIL',
}

export enum LOGOUT {
  REQUEST = 'LOGOUT_REQUEST',
  SUCCESS = 'LOGOUT_SUCCESS',
  FAIL = 'LOGOUT_FAIL',
}

export enum AUTHORIZATION_WITH_GOOGLE {
  REQUEST = 'AUTH/AUTHORIZATION_WITH_GOOGLE_REQUEST',
  SUCCESS = 'AUTH/AUTHORIZATION_WITH_GOOGLE_SUCCESS',
  FAIL = 'AUTH/AUTHORIZATION_WITH_GOOGLE_FAIL',
}

export enum CLEAR {
  ERRORS_REQUEST = 'CLEAR/CLEAR_ERRORS',
}
