export enum COMMUNITIES {
  GET_DATA_REQUEST = 'COMMUNITIES/GET_DATA_REQUEST',
  GET_DATA_SUCCESS = 'COMMUNITIES/GET_DATA_SUCCESS',
  GET_DATA_FAIL = 'COMMUNITIES/GET_DATA_FAIL',

  GET_COMMUNITY_BY_ID_REQUEST = 'COMMUNITIES/GET_COMMUNITY_BY_ID_REQUEST',
  GET_COMMUNITY_BY_ID_SUCCESS = 'COMMUNITIES/GET_COMMUNITY_BY_ID_SUCCESS',
  GET_COMMUNITY_BY_ID_FAIL = 'COMMUNITIES/GET_COMMUNITY_BY_ID_FAIL',
  GET_COMMUNITY_BY_ID_CLEAR = 'COMMUNITIES/GET_COMMUNITY_BY_ID_CLEAR',

  GET_MANAGING_COMMUNITIES_REQUEST = 'COMMUNITIES/GET_MANAGING_COMMUNITIES_REQUEST',
  GET_MANAGING_COMMUNITIES_SUCCESS = 'COMMUNITIES/GET_MANAGING_COMMUNITIES_SUCCESS',
  GET_MANAGING_COMMUNITIES_FAIL = 'COMMUNITIES/GET_MANAGING_COMMUNITIES_FAIL',

  CHANGE_INFORMATION_COMMUNITY_REQUEST = 'COMMUNITIES/CHANGE_INFORMATION_COMMUNITY_REQUEST',
  CHANGE_INFORMATION_COMMUNITY_SUCCESS = 'COMMUNITIES/CHANGE_INFORMATION_COMMUNITY_SUCCESS',
  CHANGE_INFORMATION_COMMUNITY_FAIL = 'COMMUNITIES/CHANGE_INFORMATION_COMMUNITY_FAIL',

  CHANGE_INFORMATION_VALUE = 'COMMUNITIES/CHANGE_INFORMATION_VALUE',

  CREATE_REQUEST = 'COMMUNITIES/CREATE_REQUEST',
  CREATE_SUCCESS = 'COMMUNITIES/CREATE_SUCCESS',
  CREATE_FAIL = 'COMMUNITIES/CREATE_FAIL',

  START_FOLLOWING_REQUEST = 'COMMUNITIES/START_FOLLOWING_REQUEST',
  START_FOLLOWING_SUCCESS = 'COMMUNITIES/START_FOLLOWING_SUCCESS',
  START_FOLLOWING_FAIL = 'COMMUNITIES/START_FOLLOWING_FAIL',

  CANCEL_FOLLOWING_REQUEST = 'COMMUNITIES/CANCEL_FOLLOWING_REQUEST',
  CANCEL_FOLLOWING_SUCCESS = 'COMMUNITIES/CANCEL_FOLLOWING_SUCCESS',
  CANCEL_FOLLOWING_FAIL = 'COMMUNITIES/CANCEL_FOLLOWING_FAIL',

  CLEAR_DATA = 'COMMUNITIES/CLEAR_DATA',

  REMOVE_COMMUNITY_REQUEST = 'COMMUNITIES/REMOVE_COMMUNITY_REQUEST',
  REMOVE_COMMUNITY_SUCCESS = 'COMMUNITIES/REMOVE_COMMUNITY_SUCCESS',
  REMOVE_COMMUNITY_FAIL = 'COMMUNITIES/REMOVE_COMMUNITY_FAIL',
}
