export enum COMMUNITIES {
  GET_DATA_REQUEST = 'COMMUNITIES/GET_DATA_REQUEST',
  GET_DATA_SUCCESS = 'COMMUNITIES/GET_DATA_SUCCESS',
  GET_DATA_FAIL = 'COMMUNITIES/GET_DATA_FAIL',

  CREATE_REQUEST = 'COMMUNITIES/CREATE_REQUEST',
  CREATE_SUCCESS = 'COMMUNITIES/CREATE_SUCCESS',
  CREATE_FAIL = 'COMMUNITIES/CREATE_FAIL',

  START_FOLLOWING_REQUEST = 'COMMUNITIES/START_FOLLOWING_REQUEST',
  START_FOLLOWING_SUCCESS = 'COMMUNITIES/START_FOLLOWING_SUCCESS',
  START_FOLLOWING_FAIL = 'COMMUNITIES/START_FOLLOWING_FAIL',

  CANCEL_FOLLOWING_REQUEST = 'COMMUNITIES/CANCEL_FOLLOWING_REQUEST',
  CANCEL_FOLLOWING_SUCCESS = 'COMMUNITIES/CANCEL_FOLLOWING_SUCCESS',
  CANCEL_FOLLOWING_FAIL = 'COMMUNITIES/CANCEL_FOLLOWING_FAIL',

  CLEAR_DATA = 'COMMUNITIES/CLEAR_DATA',
}
