export enum EVENT {
  EVENT_CREATE_REQUEST = 'EVENT/EVENT_CREATE_REQUEST',
  EVENT_CREATE_SUCCESS = 'EVENT/EVENT_CREATE_SUCCESS',
  EVENT_CREATE_FAIL = 'EVENT/EVENT_CREATE_FAIL',

  GET_EVENT_BY_COMMUNITY_REQUEST = 'EVENT/GET_EVENT_BY_COMMUNITY_REQUEST',
  GET_EVENT_BY_COMMUNITY_SUCCESS = 'EVENT/GET_EVENT_BY_COMMUNITY_SUCCESS',
  GET_EVENT_BY_COMMUNITY_FAIL = 'EVENT/GET_EVENT_BY_COMMUNITY_FAIL',

  GET_MANAGING_EVENTS_REQUEST = 'COMMUNITIES/GET_MANAGING_EVENTS_REQUEST',
  GET_MANAGING_EVENTS_SUCCESS = 'COMMUNITIES/GET_MANAGING_EVENTS_SUCCESS',
  GET_MANAGING_EVENTS_FAIL = 'COMMUNITIES/GET_MANAGING_EVENTS_FAIL',

  GET_EVENT_BY_ID_REQUEST = 'EVENT/GET_EVENT_BY_ID_REQUEST',
  GET_EVENT_BY_ID_SUCCESS = 'EVENT/GET_EVENT_BY_ID_SUCCESS',
  GET_EVENT_BY_ID_FAIL = 'EVENT/GET_EVENT_BY_ID_FAIL',
  GET_EVENT_BY_ID_CLEAR = 'EVENT/GET_EVENT_BY_ID_CLEAR',

  GET_EVENTS_REQUEST = 'EVENTS/GET_EVENTS_REQUEST',
  GET_EVENTS_SUCCESS = 'EVENT/GET_EVENTS_SUCCESS',
  GET_EVENTS_FAIL = 'EVENT/GET_EVENTS_FAIL',

  START_ATTEND_EVENT_REQUEST = 'EVENT/START_ATTEND_EVENT_REQUEST',
  START_ATTEND_EVENT_SUCCESS = 'EVENT/START_ATTEND_EVENT_SUCCESS',
  START_ATTEND_EVENT_FAIL = 'EVENT/START_ATTEND_EVENT_FAIL',

  END_ATTEND_EVENT_REQUEST = 'EVENT/END_ATTEND_EVENT_REQUEST',
  END_ATTEND_EVENT_SUCCESS = 'EVENT/END_ATTEND_EVENT_SUCCESS',
  END_ATTEND_EVENT_FAIL = 'EVENT/END_ATTEND_EVENT_FAIL',

  CHANGE_INFORMATION_EVENT_REQUEST = 'EVENT/CHANGE_INFORMATION_EVENT_REQUEST',
  CHANGE_INFORMATION_EVENT_SUCCESS = 'EVENT/CHANGE_INFORMATION_EVENT_SUCCESS',
  CHANGE_INFORMATION_EVENT_FAIL = 'EVENT/CHANGE_INFORMATION_EVENT_FAIL',
  CHANGE_INFORMATION_VALUE = 'EVENT/CHANGE_INFORMATION_VALUE',

  REMOVE_EVENT_REQUEST = 'EVENT/REMOVE_EVENT_REQUEST',
  REMOVE_EVENT_SUCCESS = 'EVENT/REMOVE_EVENT_SUCCESS',
  REMOVE_EVENTY_FAIL = 'EVENT/REMOVE_EVENT_FAIL',

  SET_OFFSET = 'EVENTS/SET_OFFSET',
  SET_LIMIT = 'EVENTS/SET_LIMIT',
}
