export enum EVENT {
  EVENT_CREATE_REQUEST = 'EVENT/EVENT_CREATE_REQUEST',
  EVENT_CREATE_SUCCESS = 'EVENT/EVENT_CREATE_SUCCESS',
  EVENT_CREATE_FAIL = 'EVENT/EVENT_CREATE_FAIL',

  GET_EVENT_BY_ID_REQUEST = 'EVENT/GET_EVENT_BY_ID_REQUEST',
  GET_EVENT_BY_ID_SUCCESS = 'EVENT/GET_EVENT_BY_ID_SUCCESS',
  GET_EVENT_BY_ID_FAIL = 'EVENT/GET_EVENT_BY_ID_FAIL',

  GET_EVENTS_REQUEST = 'EVENTS/GET_EVENTS_REQUEST',
  GET_EVENTS_SUCCESS = 'EVENT/GET_EVENTS_SUCCESS',
  GET_EVENTS_FAIL = 'EVENT/GET_EVENTS_FAIL',

  START_ATTEND_EVENT_REQUEST = 'EVENT/START_ATTEND_EVENT_REQUEST',
  START_ATTEND_EVENT_SUCCESS = 'EVENT/START_ATTEND_EVENT_SUCCESS',
  START_ATTEND_EVENT_FAIL = 'EVENT/START_ATTEND_EVENT_FAIL',

  CHANGE_INFORMATION_EVENT_REQUEST = 'EVENT/CHANGE_INFORMATION_EVENT_REQUEST',
  CHANGE_INFORMATION_EVENT_SUCCESS = 'EVENT/CHANGE_INFORMATION_EVENT_SUCCESS',
  CHANGE_INFORMATION_EVENT_FAIL = 'EVENT/CHANGE_INFORMATION_EVENT_FAIL',
  CHANGE_INFORMATION_VALUE = 'EVENT/CHANGE_INFORMATION_VALUE',
}
