export enum PEOPLE {
  REQUEST = 'PEOPLE/PEOPLE_REQUEST',
  SUCCESS = 'PEOPLE/PEOPLE_SUCCESS',
  FAIL = 'PEOPLE/PEOPLE_FAIL',
}
export enum DIFFERENT_USER {
  REQUEST = 'DIFFERENT_USER/DIFFERENT_USER_REQUEST',
  SUCCESS = 'DIFFERENT_USER/DIFFERENT_USER_SUCCESS',
  FAIL = 'DIFFERENT_USER/DIFFERENT_USER_FAIL',
}
