export enum PROFILE {
  GET_DATA_REQUEST = 'PROFILE/GET_DATA_REQUEST',
  GET_DATA_SUCCESS = 'PROFILE/GET_DATA_SUCCESS',
  GET_DATA_FAIL = 'PROFILE/GET_DATA_FAIL',

  CLEAR_USER_DATA = 'PROFILE/CLEAR_USER_DATA',
}
