export enum PROFILE {
  GET_DATA_REQUEST = 'PROFILE/GET_DATA_REQUEST',
  GET_DATA_SUCCESS = 'PROFILE/GET_DATA_SUCCESS',
  GET_DATA_FAIL = 'PROFILE/GET_DATA_FAIL',

  GET_USER_BY_ID_REQUEST = 'PROFILE/GET_USER_BY_ID_REQUEST',
  GET_USER_BY_ID_SUCCESS = 'PROFILE/GET_USER_BY_ID_SUCCESS',
  GET_USER_BY_ID_FAIL = 'PROFILE/GET_USER_BY_ID_FAIL',

  CLEAR_USER_DATA = 'PROFILE/CLEAR_USER_DATA',
}
