export enum PROFILE {
  GET_DATA_REQUEST = 'PROFILE/GET_DATA_REQUEST',
  GET_DATA_SUCCESS = 'PROFILE/GET_DATA_SUCCESS',
  GET_DATA_FAIL = 'PROFILE/GET_DATA_FAIL',

  GET_USER_BY_ID_REQUEST = 'PROFILE/GET_USER_BY_ID_REQUEST',
  GET_USER_BY_ID_SUCCESS = 'PROFILE/GET_USER_BY_ID_SUCCESS',
  GET_USER_BY_ID_FAIL = 'PROFILE/GET_USER_BY_ID_FAIL',

  CHANGE_DATA_REQUEST = 'PROFILE/CHANGE_DATA_REQUEST',
  CHANGE_DATA_SUCCESS = 'PROFILE/CHANGE_DATA_SUCCESS',
  CHANGE_DATA_FAIL = 'PROFILE/CHANGE_DATA_FAIL',

  CHANGE_DANCE_STYLES_REQUEST = 'PROFILE/CHANGE_DANCE_STYLES_REQUEST',
  CHANGE_DANCE_STYLES_SUCCESS = 'PROFILE/CHANGE_DANCE_STYLES_SUCCESS',
  CHANGE_DANCE_STYLES_FAIL = 'PROFILE/CHANGE_DANCE_STYLES_FAIL',

  CHANGE_USER_COUNTRY_REQUEST = 'PROFILE/CHANGE_USER_COUNTRY_REQUEST',
  CHANGE_USER_COUNTRY_SUCCESS = 'PROFILE/CHANGE_USER_COUNTRY_SUCCESS',
  CHANGE_USER_COUNTRY_FAIL = 'PROFILE/CHANGE_USER_COUNTRY_FAIL',

  CHANGE_PASSWORD_REQUEST = 'PROFILE/CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS = 'PROFILE/CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAIL = 'PROFILE/CHANGE_PASSWORD_FAIL',
  CHANGE_PASSWORD_CLEAR = 'PROFILE/CHANGE_PASSWORD_CLEAR',

  CLEAR_USER_DATA = 'PROFILE/CLEAR_USER_DATA',
}
