export enum TICKET {
  TICKET_CREATE_REQUEST = 'TICKET/TICKET_CREATE_REQUEST',
  TICKET_CREATE_SUCCESS = 'TICKET/TICKET_CREATE_SUCCESS',
  TICKET_CREATE_FAIL = 'TICKET/TICKET_CREATE_FAIL',

  GET_TICKET_BY_ID_REQUEST = 'TICKET/GET_TICKET_BY_ID_REQUEST',
  GET_TICKET_BY_ID_SUCCESS = 'TICKET/GET_TICKET_BY_ID_SUCCESS',
  GET_TICKET_BY_ID_FAIL = 'TICKET/GET_TICKET_BY_ID_FAIL',
  GET_TICKET_BY_ID_CLEAR = 'TICKET/GET_TICKET_BY_ID_CLEAR',

  GET_TICKETS_REQUEST = 'TICKETS/GET_TICKETS_REQUEST',
  GET_TICKETS_SUCCESS = 'TICKET/GET_TICKETS_SUCCESS',
  GET_TICKETS_FAIL = 'TICKET/GET_TICKETS_FAIL',

  CHANGE_INFORMATION_TICKET_REQUEST = 'TICKET/CHANGE_INFORMATION_TICKET_REQUEST',
  CHANGE_INFORMATION_TICKET_SUCCESS = 'TICKET/CHANGE_INFORMATION_TICKET_SUCCESS',
  CHANGE_INFORMATION_TICKET_FAIL = 'TICKET/CHANGE_INFORMATION_TICKET_FAIL',

  REMOVE_TICKET_REQUEST = 'TICKET/REMOVE_TICKET_REQUEST',
  REMOVE_TICKET_SUCCESS = 'TICKET/REMOVE_TICKET_SUCCESS',
  REMOVE_TICKETY_FAIL = 'TICKET/REMOVE_TICKET_FAIL',

  CREATE_TICKET_AFTER_EVENT_REQUEST = 'TICKET/CREATE_TICKET_AFTER_EVENT_REQUEST',
  CREATE_TICKET_AFTER_EVENT_SUCCESS = 'TICKET/CREATE_TICKET_AFTER_EVENT_SUCCESS',
  CREATE_TICKET_AFTER_EVENT_FAIL = 'TICKET/CREATE_TICKET_AFTER_EVENT_FAIL',

  GET_PURCHASED_TICKETS_REQUEST = 'TICKETS/GET_PURCHASED_TICKETS_REQUEST',
  GET_PURCHASED_TICKETS_SUCCESS = 'TICKET/GET_PURCHASED_TICKETS_SUCCESS',
  GET_PURCHASED_TICKETS_FAIL = 'TICKET/GET_PURCHASED_TICKETS_FAIL',

  CLEAR_PURCHASED_TICKETS_VALUE = 'TICKET/CLEAR_PURCHASED_TICKETS_VALUE',
}

export enum BASKET_TICKET {
  ADD_TO_BASKET_TICKET = 'BASKET_TICKET/ADD_TO_BASKET_TICKET',
  RESET_QUANTITY = 'BASKET_TICKET/RESET_QUANTITY',
  CLEAR_BASKET = 'BASKET_TICKET/CLEAR_BASKET',
}
