export default {
  isLoading: '',
  name: '',
  description: '',
  country: '',
  location: '',
  creatorUid: '',
  categories: '',
  followers: '',
  images: '',
  errors: '',
  eventsList: [],
  eventsByIdData: [],
  eventUid: '',
  eventDate: '',
  place: '',
  communityUid: '',
};
