export default {
  isLoading: '',
  name: '',
  description: '',
  country: '',
  location: '',
  creatorUid: '',
  categories: '',
  followers: '',
  images: '',
  errors: '',
  eventsList: [],
  eventsByIdCommunity: [],
  managingEvents: [],
  loadingManaging: false,
  eventUid: '',
  eventDate: '',
  place: '',
  communityUid: '',
  price: '',
};
