export default {
  // name: '',
  // location: '',
  // role: '',
  // gender: '',
  // country: '',
  errors: null,
  userData: null,
  userUid: '',
  userByIdData: null,
  name: '',
  gender: '',
  profileImg: {},
  newPassword: '',
  changePasswordSuccess: false,
  changePasswordErrors: null,
  userCountry: '',
};
