export default {
  email: '',
  password: '',
  isLoading: false,
  isAuthorized: false,
  errors: null,
  currentUser: null,
  name: '',
  gender: '',
  country: '',
  location: '',
  role: '',
  isRegistrationsSuccess: false,
  isUserExists: false,
  individualStyles: [],
  token: '',
};
